config.patch:
  route_name: config.patch
  title: 'Patch'
  base_route: config.sync

config.patch.per_plugin:
  route_name: config.patch_per_plugin
  deriver: 'Drupal\config_patch\Plugin\Derivative\OutputLocalTasks'
  parent_id: config.patch

config_patch.settings:
  route_name: config_patch.settings
  title: 'Global Settings'
  base_route: config_patch.settings
