config.patch:
  route_name: config.patch
  title: 'Patch'
  base_route: config.sync

config_patch.settings:
  route_name: config_patch.settings
  title: 'Global Settings'
  base_route: config_patch.settings